迁移模型on_delete BUG
解决TypeError: __init__() missing 1 required positional argument: 'on_delete'
models.ForeignKey('Topic',on_delete=models.CASCADE)